### ISSUE TITLE
[REPOSITORY] New Repository required for Sample polling repository proxy connector 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-connector-repository-file-sample#2]
### Name

egeria-connector-repository-file-sample

### Owner

davidradl

### Deliverable

Provides a repository proxy sample that uses polling. The target is a file folder 

### Build, test and CI-CD process

How will the deliverables identified above be created & distributed? jar file like the other repository connectors that are in other repositories (e.g. Atlas) 
Will maven, gradle (preferred for new repos) be used? Gradle
What languages are used - Python, Java, Go, .... are particular versions needed? Java 11 or above
will a container image be required? Not sure
What should be checked before a PR can be merged? CTS if a large change.
How about after merging, on main? CTS if a large change.
Are additional tests needed?

### Dependencies

none

### Justification

Agreed by the community - as its lifecycle is different from the egeria-samples content. Issue odpi/egeria-connector-repository-file-sample#3 documents more details.   

### Assumptions

Yes - all true

### Additional Information

Not for production use. 

### Work Plan

Before creating the repo
- [x] review overall request & get clarifications
- [x] get approval on developer/TSC call from maintainers

Creating the repo
- [x] Create the repo under the odpi organization (default gitignore, license, readme)
- [x] Setup branch protection rules
- [x] Set pull request options (allow merge, squash, rebase, suggest updating, allow automerge, do not delete head)
- [x] Update security settings in repo (policy, advisories, alerts)
- [x] set up permissions

First steps
- [x] Initial code-drop (author)

Getting CI/CD started & refining settings
- [x] Add initial build script for PR (including gradle wrapper if required)
- [x] Add initial build script for merge

Further Refinement
- [x] Add link in egeria docs to new repo describing purpose ( https://github.com/odpi/egeria-docs/blob/main/site/docs/education/tutorials/git-and-git-hub-tutorial/egeria-git-repositories.md ) 
- [x] Add to connector catalog, if new repo is for connector ( https://github.com/odpi/egeria-docs/blob/main/site/docs/connectors/index.md )
- [x] Add to release process docs ( https://github.com/odpi/egeria-docs/blob/main/site/docs/guides/contributor/release-process/index.md )
- [x] Add required credentials for publishing to container repos, maven central etc
- [x] Add artifact signing if needed
- [x] Add dependabot config        
- [x] Add CodeQL 
- [x] Add to LFX ( https://projectadmin.lfx.linuxfoundation.org/project/a092M00001IV4JtQAL  ) for
  - [x] LFXSecurity
  - [x] LFAnalytics
- [x] Add check for stale defects
- [x] Add any required issue tags

Release
- [x] Add release pipeline

**Comment by davidradl** [comment]
@planetf1 I have tried to bring in the code locally and I am getting 
`FAILURE: Build failed with an exception.

* Where:
Build file '/Users/davidradley/egeria-connector-repository-file-sample/build.gradle' line: 8

* What went wrong:
An exception occurred applying plugin request [id: 'com.github.johnrengelman.shadow', version: '7.1.2']
> Failed to apply plugin class 'com.github.jengelman.gradle.plugins.shadow.ShadowBasePlugin'.
   > This version of Shadow supports Gradle 7.0+ only. Please upgrade.
`
Should I be running gradle 7 or 8?

**Comment by planetf1** [comment]
There is still some items remaining (ie LFX so reopening and assigning)

**Comment by planetf1** [comment]
Keeping open - still some docs/update tasks to do (some are blocked on LF open issues)

**Comment by planetf1** [comment]
I think all we need for now is done (there is no release)
